package mud

var strengthClassNameMap map[byte]string
var skillClassNameMap map[byte]string
var fullTitleMap map[byte]string

// Strengths
const (
	MELEESECONDARY = byte(1)
	RANGESECONDARY = byte(2)
	MAGICSECONDARY = byte(3)
	MELEEPRIMARY   = byte(4)
	RANGEPRIMARY   = byte(8)
	MAGICPRIMARY   = byte(12)
)

// Skills
const (
	CUNNINGSECONDARY  = byte(16)
	ORDERLYSECONDARY  = byte(32)
	CREATIVESECONDARY = byte(48)
	CUNNINGPRIMARY    = byte(64)
	ORDERLYPRIMARY    = byte(128)
	CREATIVEPRIMARY   = byte(192)
)

// Masks for strengths/skills
const (
	SECONDARYSTRENGTHMASK = byte(3)
	PRIMARYSTRENGTHMASK   = byte(12)
	SECONDARYSKILLMASK    = byte(48)
	PRIMARYSKILLMASK      = byte(192)
)

// ClassInfo handles user/NPC class orientation
type ClassInfo interface {
	ClassInfo() byte
	SetClassInfo(byte)

	Strengths() (byte, byte)
	SetStrengths(byte, byte)
	Skills() (byte, byte)
	SetSkills(byte, byte)
}

// GetSubTitles takes strengths and gives a class title
func GetSubTitles(strengthPrimary, strengthSecondary, skillPrimary, skillSecondary byte) (string, string) {
	strS, sklS := "Hippopotamus", "Spaghetti"

	strK, sK := strengthClassNameMap[strengthPrimary|strengthSecondary]

	if sK {
		strS = strK
	}

	sklK, lK := skillClassNameMap[skillPrimary|skillSecondary]

	if lK {
		sklS = sklK
	}

	return strS, sklS
}

// GetTitle takes strengths and gives a class title
func GetTitle(strengthPrimary, strengthSecondary, skillPrimary, skillSecondary byte) string {
	title := "Unworthy"

	newTitle, ok := fullTitleMap[strengthPrimary|strengthSecondary|skillPrimary|skillSecondary]

	if ok {
		title = newTitle
	}

	return title
}

func init() {
	strengthClassNameMap = map[byte]string{
		MELEEPRIMARY | MELEESECONDARY: "Warrior",
		MELEEPRIMARY | MAGICSECONDARY: "Paladin",
		MAGICPRIMARY | MELEESECONDARY: "Cleric",
		MAGICPRIMARY | MAGICSECONDARY: "Mage",
		MAGICPRIMARY | RANGESECONDARY: "Warlock",
		RANGEPRIMARY | MAGICSECONDARY: "Caster",
		RANGEPRIMARY | RANGESECONDARY: "Sniper",
		RANGEPRIMARY | MELEESECONDARY: "Archer",
		MELEEPRIMARY | RANGESECONDARY: "Ranger"}

	skillClassNameMap = map[byte]string{
		CREATIVEPRIMARY | CREATIVESECONDARY: "Artist",
		CREATIVEPRIMARY | CUNNINGSECONDARY:  "Performer",
		CUNNINGPRIMARY | CREATIVESECONDARY:  "Hawker",
		CUNNINGPRIMARY | CUNNINGSECONDARY:   "Orator",
		CUNNINGPRIMARY | ORDERLYSECONDARY:   "Hunter",
		ORDERLYPRIMARY | CUNNINGSECONDARY:   "Merchant",
		ORDERLYPRIMARY | ORDERLYSECONDARY:   "Adviser",
		ORDERLYPRIMARY | CREATIVESECONDARY:  "Scholar",
		CREATIVEPRIMARY | ORDERLYSECONDARY:  "Engineer"}

	fullTitleMap = map[byte]string{
		MELEEPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Martial Artist",
		MELEEPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Swordslinger",
		MELEEPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Bodybuilder",
		MELEEPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Strategist",
		MELEEPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Tracker",
		MELEEPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Pilgrim",
		MELEEPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Monk",
		MELEEPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Warrior-Poet",
		MELEEPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Sapper",
		MELEEPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Epic Poet",
		MELEEPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Paladin of the Arts",
		MELEEPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Paladin of the Corners",
		MELEEPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Great Paladin",
		MELEEPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Paladin of the Wilds",
		MELEEPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Paladin of the Bazaar",
		MELEEPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Paladin of Wisdom",
		MELEEPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Paladin of History",
		MELEEPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Paladin-Toolmaker",
		MAGICPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Potion Tinker",
		MAGICPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Poisoner",
		MAGICPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Potionmaker",
		MAGICPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Summoner of Elements",
		MAGICPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Cleric of the Hunt",
		MAGICPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Cleric of the Trail",
		MAGICPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Cleric of Order",
		MAGICPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Swift Cleric",
		MAGICPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Apothecary",
		MAGICPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Conjurer of Images",
		MAGICPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Image Storyteller",
		MAGICPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Mindthief Mage",
		MAGICPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Spellcaster",
		MAGICPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Mageseeker",
		MAGICPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Mage of Fortune",
		MAGICPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Seer",
		MAGICPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Arcane Historian",
		MAGICPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Spiremaker",
		MAGICPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Elementwright",
		MAGICPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Enthraller",
		MAGICPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Battlemage Strategist",
		MAGICPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Summoner Warlock",
		MAGICPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Dark Warlock",
		MAGICPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Warlock of Fortune",
		MAGICPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Wise Warlock",
		MAGICPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Battlemage Scholar",
		MAGICPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Battlemage Commander",
		RANGEPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Cloudmaster",
		RANGEPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Stealthwalker",
		RANGEPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Escape Artist",
		RANGEPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Summoner Caster",
		RANGEPRIMARY | MAGICSECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Stealth Caster",
		RANGEPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Caster of the Trail",
		RANGEPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Wise Caster",
		RANGEPRIMARY | MAGICSECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Caster Tinker",
		RANGEPRIMARY | MAGICSECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Obstacle Destroyer",
		RANGEPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Expert in Confusion",
		RANGEPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Expert in Redirection",
		RANGEPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Expert in Deception",
		RANGEPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Master of Disguise",
		RANGEPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Deepwood Hunter",
		RANGEPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Ranged Strategist",
		RANGEPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Master Sniper",
		RANGEPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Target Shooter",
		RANGEPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Demolitionist",
		RANGEPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Improvisation Artist",
		RANGEPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Crowd Pleaser",
		RANGEPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Stealth Archer",
		RANGEPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "Assassin",
		RANGEPRIMARY | MELEESECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Trapper",
		RANGEPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Archer of Fortune",
		RANGEPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Skill Shot",
		RANGEPRIMARY | MELEESECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Arrowmaster",
		RANGEPRIMARY | MELEESECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Trick Shot",
		MELEEPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | CREATIVESECONDARY: "Vagabond",
		MELEEPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | CUNNINGSECONDARY:  "Rogue",
		MELEEPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | CREATIVESECONDARY:  "Expert Trader",
		MELEEPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | CUNNINGSECONDARY:   "People's Champion",
		MELEEPRIMARY | RANGESECONDARY | CUNNINGPRIMARY | ORDERLYSECONDARY:   "Warden of the Hunt",
		MELEEPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | CUNNINGSECONDARY:   "Ranger of Fortune",
		MELEEPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | ORDERLYSECONDARY:   "Scout",
		MELEEPRIMARY | RANGESECONDARY | ORDERLYPRIMARY | CREATIVESECONDARY:  "Nature Spirit",
		MELEEPRIMARY | RANGESECONDARY | CREATIVEPRIMARY | ORDERLYSECONDARY:  "Bridgebuilder"}
}
